# Dependency Versions
dependencies.minecraft_dependency=>=26.1 <26.2
dependencies.minecraft_version=26.1.2
dependencies.authlib_version=70063
dependencies.forge_version=64.0.8
loom.platform=forge

action.minecraft_version=26.1.2
action.mod_loader=forge
action.loader_version=64.0.8
action.java_version=25
