plugins {
    id("gg.essential.loom").version("${essential_loom_version}").apply(false)
    id("com.replaymod.preprocess").version("${preprocessor_version}")
    id("org.ajoberstar.grgit").version("${grgit_version}")
    id("io.freefair.lombok").version("${lombok_version}")
}

preprocess {
    strictExtraMappings = false

    var mc11404_fabric = createNode("1.14.4-fabric", 1_14_04, 'mojang')
    var mc11502_fabric = createNode("1.15.2-fabric", 1_15_02, 'mojang')
    var mc11603_fabric = createNode("1.16.3-fabric", 1_16_03, 'mojang')

    mc11502_fabric.link(mc11404_fabric, null)
    mc11603_fabric.link(mc11502_fabric, file("versions/mappings-1.16.3-to-1.15.txt"))


    var mc11404_forge = createNode("1.14.4-forge", 1_14_04, 'mojang')
    var mc11502_forge = createNode("1.15.2-forge", 1_15_02, 'mojang')
    var mc11603_forge = createNode("1.16.3-forge", 1_16_03, 'mojang')

    mc11603_fabric.link(mc11603_forge, null)

    mc11502_forge.link(mc11404_forge, null)
    mc11603_forge.link(mc11502_forge, file("versions/mappings-1.16.3-to-1.15.txt"))

    for (final def node in getNodes()) {
        findProject(node.project).ext.mcVersion = node.mcVersion
        var modPlatform = "none"
        if (node.project.endsWith("-fabric")) {
            modPlatform = "fabric"
        } else if (node.project.endsWith("-forge")) {
            modPlatform = "forge"
        } else if (node.project.endsWith("-neoforge")) {
            modPlatform = "neoforge"
        } else if (node.project.endsWith("-quilt")) {
            modPlatform = "quilt"
        }
        findProject(node.project).ext.modPlatform = modPlatform
    }
}

ext {
    Map env = System.getenv()
    File localPropsFile = file("${rootDir}/local.properties")

    if (localPropsFile.exists()) {
        Properties p = new Properties()
        p.load(new FileInputStream(localPropsFile))
        p.each { key, value ->
            ext[key as String] = value
        }
    }

    getEnv = {
        return env
    }

    getOrDefault = { String key, String defaultValue ->
        String value
        (value = project.findProperty(key)) && !value.isEmpty() ? value : defaultValue
    }

    getVersionSuffix = {
        String number = env.GITHUB_RUN_NUMBER ? env.GITHUB_RUN_NUMBER : 'x'
        String type = env.BUILD_TYPE
        switch (type) {
            case 'release': return ''
            case 'beta': return "+snapshot.${number}"
            case 'alpha': return "+pr.${number}"
        }
        return "+build.${number}"
    }

    getVersion = { Project proj ->
        return "${proj.property("mod.version")}${getVersionSuffix()}"
    }
}

tasks.register("genLocalProperties") {
    it.group("${project.property("mod.id")}")

    doFirst {
        File localPropsFile = file("${rootDir}/local.properties")

        if (localPropsFile.exists()) {
            throw new IllegalStateException("local.properties file already generated. If you want to regenerate it, please delete it manually first")
        } else {
            BufferedWriter bufferedWriter = new BufferedWriter(new FileWriter(localPropsFile))
            bufferedWriter.writeLine("# Secrets")
            bufferedWriter.writeLine("secrets.gpg.signingKey=")
            bufferedWriter.writeLine("secrets.gpg.signingPassword=")
            bufferedWriter.writeLine("secrets.mavenCentral.username=")
            bufferedWriter.writeLine("secrets.mavenCentral.password=")
            bufferedWriter.writeLine('')
            bufferedWriter.writeLine("# Overwritten configurations")
            bufferedWriter.writeLine("ow.build.environment.local=")
            bufferedWriter.writeLine("ow.build.environment.buildType=")
            bufferedWriter.writeLine("ow.game.window.width=")
            bufferedWriter.writeLine("ow.game.window.height=")
            bufferedWriter.writeLine("ow.game.window.username=")
            bufferedWriter.close()

            project.getLogger().info("local.properties generated successfully!")
        }
    }
}

tasks.register("cleanPreprocessSources") {
    it.group("${project.mod_id}")

    doFirst {
        subprojects {
            def path = project.projectDir.toPath().resolve("build/preprocessed")
            path.toFile().deleteDir()
        }
    }
}

tasks.register("copyAllJars", Copy) {
    var libs = it.rootSpec.addChild()
    var devlibs = it.rootSpec.addChild()
    subprojects.forEach { subproject ->
        libs.from(subproject.layout.buildDirectory.dir("libs")) {
            include("*.jar")
        }
        devlibs.from(subproject.layout.buildDirectory.dir("devlibs")) {
            include("*.jar")
        }
    }
    doFirst {
        delete layout.buildDirectory.dir("libs")
        delete layout.buildDirectory.dir("devlibs")
    }
    into(layout.buildDirectory)
    libs.into("libs")
    devlibs.into("devlibs")
    it.with(libs, devlibs)
    duplicatesStrategy = DuplicatesStrategy.INCLUDE
}
