plugins {
    alias libs.plugins.architectury.remap apply false
    alias libs.plugins.architectury.noremap apply false
    alias libs.plugins.preprocessor
    alias libs.plugins.lombok
}

preprocess {
    strictExtraMappings = false

    var mc12110_fabric = createNode("1.21.10-fabric", 1_21_10, 'mojang')
    var mc260102_fabric = createNode("26.1.2-fabric", 26_01_02, 'mojang')
    var mc260200_fabric = createNode("26.2-fabric", 26_02_00, 'mojang')

    mc12110_fabric.link(mc260102_fabric, null)
    mc260102_fabric.link(mc260200_fabric, null)

    var mc12110_forge = createNode("1.21.10-forge", 1_21_10, 'mojang')
    var mc260102_forge = createNode("26.1.2-forge", 26_01_02, 'mojang')
    var mc260200_forge = createNode("26.2-forge", 26_02_00, 'mojang')

    mc12110_fabric.link(mc12110_forge, null)
    mc12110_forge.link(mc260102_forge, null)
    mc260102_forge.link(mc260200_forge, null)

    var mc12110_neoforge = createNode("1.21.10-neoforge", 1_21_10, 'mojang')
    var mc260102_neoforge = createNode("26.1.2-neoforge", 26_01_02, 'mojang')
    var mc260200_neoforge = createNode("26.2-neoforge", 26_02_00, 'mojang')

    mc12110_forge.link(mc12110_neoforge, null)
    mc12110_neoforge.link(mc260102_neoforge, null)
    mc260102_neoforge.link(mc260200_neoforge, null)

    for (final def node in getNodes()) {
        findProject(node.project).ext.mcVersion = node.mcVersion
        var modPlatform = "none"
        if (node.project.endsWith("-fabric")) {
            modPlatform = "fabric"
        } else if (node.project.endsWith("-forge")) {
            modPlatform = "forge"
        } else if (node.project.endsWith("-neoforge")) {
            modPlatform = "neoforge"
        } else if (node.project.endsWith("-quilt")) {
            modPlatform = "quilt"
        }
        findProject(node.project).ext.modPlatform = modPlatform
    }
}

ext {
    Map env = System.getenv()
    File localPropsFile = file("${rootDir}/local.properties")

    if (localPropsFile.exists()) {
        Properties p = new Properties()
        p.load(new FileInputStream(localPropsFile))
        p.each { key, value ->
            ext[key as String] = value
        }
    }

    getEnv = {
        return env
    }

    getOrDefault = { String key, String defaultValue ->
        String value
        (value = project.findProperty(key)) && !value.isEmpty() ? value : defaultValue
    }

    getVersionSuffix = {
        String number = env.GITHUB_RUN_NUMBER ? env.GITHUB_RUN_NUMBER : 'x'
        String type = env.VERSION_TYPE
        switch (type) {
            case 'release': return ''
            case 'beta': return "+snapshot.${number}"
            case 'alpha': return "+pr.${number}"
            default: return "+build.${number}"
        }
    }

    getModVersion = { Project proj ->
        return "${proj.property("mod.version")}${getVersionSuffix()}"
    }
}

tasks.register("cleanPreprocessSources") {
    it.group("${project.property("mod.id")}")

    doFirst {
        subprojects {
            def path = project.projectDir.toPath().resolve("build/preprocessed")
            path.toFile().deleteDir()
        }
    }
}

tasks.register("copyAllJars", Copy) {
    var libs = it.rootSpec.addChild()
    var devlibs = it.rootSpec.addChild()
    subprojects.forEach { subproject ->
        libs.from(subproject.layout.buildDirectory.dir("libs")) {
            include("*.jar")
        }
        devlibs.from(subproject.layout.buildDirectory.dir("devlibs")) {
            include("*.jar")
        }
    }
    doFirst {
        delete layout.buildDirectory.dir("libs")
        delete layout.buildDirectory.dir("devlibs")
    }
    into(layout.buildDirectory)
    libs.into("libs")
    devlibs.into("devlibs")
    it.with(libs, devlibs)
    duplicatesStrategy = DuplicatesStrategy.INCLUDE
}
