# Gradle properties
org.gradle.jvmargs=-Xmx6G -Xms2048M
systemProp.https.protocols=TLSv1,TLSv1.1,TLSv1.2

# Mod Properties
mod.archives_base_name=multiyggdrasil
mod.artifact_name=multiyggdrasil
mod.description=A mod that can provide multiple Yggdrasil servers.
mod.homepage=https://github.com/QiuShui1012/MultiYggdrasil
mod.id=multiyggdrasil
mod.license=AGPL-3.0-or-later
mod.maven_group=zh.qiushui.mod
mod.name=MultiYggdrasil
mod.sources=https://github.com/QiuShui1012/MultiYggdrasil
mod.version=1.1.0
