plugins {
    id("maven-publish")
}

final int mcVersion = project.mcVersion
final int authlibVersion = Integer.parseInt(project.property("dependencies.authlib_version") as String)
final String modPlatform = project.modPlatform

apply(plugin: "gg.essential.loom")
apply(plugin: "com.replaymod.preprocess")
apply(plugin: "io.freefair.lombok")

boolean fabricLike = modPlatform == "fabric" || modPlatform == "quilt"
boolean forgeLike = modPlatform == "forge" || modPlatform == "neoforge"

preprocess {
    vars.put("MC", mcVersion)
    vars.put("AUTHLIB", authlibVersion)
    vars.put("JAVA", java.sourceCompatibility.ordinal() + 1)
    vars.put("FABRIC", modPlatform == "fabric" ? 1 : 0)
    vars.put("FORGE", modPlatform == "forge" ? 1 : 0)
    vars.put("NEOFORGE", modPlatform == "neoforge" ? 1 : 0)
    vars.put("QUILT", modPlatform == "quilt" ? 1 : 0)
    vars.put("FABRIC_LIKE", fabricLike ? 1 : 0)
    vars.put("FORGE_LIKE", forgeLike ? 1 : 0)

    patternAnnotation.set("com.qiushui1012.mod.multiyggdrasil.util.vap.VAPPattern")
}

loom {
    silentMojangMappingsLicense()
}

repositories {
    mavenLocal()

    maven {
        name = "NeoForge"
        url = "https://maven.neoforged.net/releases"
    }

    maven {
        name = "Legacy Fabric"
        url = "https://repo.legacyfabric.net/legacyfabric"
    }

    maven {
        name = "Modrinth Maven"
        url = "https://api.modrinth.com/maven"
    }

    maven {
        name = "Curse Maven"
        url = "https://www.cursemaven.com"
    }

    maven {
        name = "Jitpack Maven"
        url = "https://jitpack.io"
    }

    maven {
        name = "Forge"
        url = "https://files.minecraftforge.net/maven"
    }

    mavenCentral()
}

dependencies {
    // Development environment
    minecraft("com.mojang:minecraft:${project.property("dependencies.minecraft_version")}")
    mappings loom.officialMojangMappings()

    api(libs.jtoml)
    include(libs.jtoml)
    switch (modPlatform) {
        case "fabric":
            implementation("com.google.code.findbugs:jsr305:3.0.2")
            modImplementation libs.fabric.loader
            break
        case "forge":
            forge("net.minecraftforge:forge:${project.property("dependencies.minecraft_version")}-${project.property("dependencies.forge_version")}")
            if (mcVersion < 11502) {
                annotationProcessor("org.spongepowered:mixin:0.8.5:processor")
                implementation("org.spongepowered:mixin:0.8.5")
            }
            compileOnly(annotationProcessor("io.github.llamalad7:mixinextras-common:0.5.3"))
            implementation(include("io.github.llamalad7:mixinextras-forge:0.5.3"))
            break
        case "neoforge":
            neoForge("net.neoforged:neoforge:${project.property("dependencies.neoforge_version")}")
            break
    }
}

sourceSets {
    if (fabricLike) {
        testmod {
            compileClasspath += main.compileClasspath
            compileClasspath += main.output
            runtimeClasspath += main.runtimeClasspath
            runtimeClasspath += main.output
            resources {
                srcDir("src/testmod/generated/resources")
                exclude("src/testmod/generated/resources/.cache")
            }
        }
    }
}

loom {
    enableTransitiveAccessWideners.set(false)

    interfaceInjection {
        enableDependencyInterfaceInjection.set(false)
        isEnabled.set(false)
    }

    if (fabricLike) {
        def path = "src/main/resources/${project.parent.property("mod.id")}.classTweaker"

        def accessWidenerFile = file(path)
        if (!accessWidenerFile.exists()) {
            accessWidenerFile = rootProject.file(path)
        }

        accessWidenerPath = accessWidenerFile

        mixin {
            // useLegacyMixinAp.set(true)
        }
    }

    if (modPlatform == "forge") {
        forge {
            convertAccessWideners.set(true)
            mixinConfig("${project.parent.property("mod.id")}.mixins.json")
        }
    }

    var isJbr = System.getProperty('java.vm.vendor').contains('JetBrains')
    runConfigs.configureEach {
        // Dump modified classes automatically.
        property("mixin.debug.export", "true")
        if (isJbr) vmArgs("-XX:+AllowEnhancedClassRedefinition")
    }

    runConfigs.named("client") {
        programArgs([
                "--username",
                project.getOrDefault("ow.game.window.username", "dev")
        ])
        runDir("run/client")
    }

    runConfigs.named("server") {
        runDir("run/server")
    }
}

base {
    setArchivesName("${project.parent.property("mod.archives_base_name")}-${project.property("dependencies.minecraft_version")}-${modPlatform}")
    setGroup("${project.property("mod.maven_group")}")
    setVersion(project.getVersion(project.parent))
}

java {
    if (mcVersion > 26_00_00) {
        sourceCompatibility = JavaVersion.VERSION_25
        targetCompatibility = JavaVersion.VERSION_25
    } else if (mcVersion > 1_21_04) {
        sourceCompatibility = JavaVersion.VERSION_21
        targetCompatibility = JavaVersion.VERSION_21
    } else if (mcVersion > 1_17_01) {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    } else if (mcVersion > 1_16_05) {
        sourceCompatibility = JavaVersion.VERSION_16
        targetCompatibility = JavaVersion.VERSION_16
    } else {
        sourceCompatibility = JavaVersion.VERSION_1_8
        targetCompatibility = JavaVersion.VERSION_1_8
    }

    withSourcesJar()
}

processResources {
    inputs.property("minecraft_dependency", project.property("dependencies.minecraft_dependency"))
    inputs.property("mod_alias", project.parent.property("mod.id"))
    inputs.property("mod_description", project.parent.property("mod.description"))
    inputs.property("mod_homepage", project.parent.property("mod.homepage"))
    inputs.property("mod_id", project.parent.property("mod.id").toString().replace("-", "_"))
    inputs.property("mod_license", project.parent.property("mod.license"))
    inputs.property("mod_name", project.parent.property("mod.name"))
    inputs.property("mod_sources", project.parent.property("mod.sources"))
    inputs.property("mod_version", project.getVersion(this.project.parent))
    inputs.property("java_version", java.sourceCompatibility.getMajorVersion())

    [
            "fabric.mod.json"            : ["fabric"],
            "pack.mcmeta"                : ["forge"],
            "META-INF"                   : ["forge", "neoforge"],
            "META-INF/mods.toml"         : ["forge", mcVersion < 12005 ? "neoforge" : "none"],
            "META-INF/neoforge.mods.toml": [mcVersion > 12004 ? "neoforge" : "none"],
            "multiyggdrasil.mixins.json" : ["fabric", "forge", "neoforge"]
    ].forEach { file, platforms ->
        if (platforms.contains(modPlatform)) {
            filesMatching(file) {
                expand([
                        "minecraft_dependency": inputs.properties.get("minecraft_dependency"),
                        "mod_alias"           : inputs.properties.get("mod_alias"),
                        "mod_description"     : inputs.properties.get("mod_description"),
                        "mod_homepage"        : inputs.properties.get("mod_homepage"),
                        "mod_id"              : inputs.properties.get("mod_id"),
                        "mod_license"         : inputs.properties.get("mod_license"),
                        "mod_name"            : inputs.properties.get("mod_name"),
                        "mod_sources"         : inputs.properties.get("mod_sources"),
                        "mod_version"         : inputs.properties.get("mod_version"),
                        "java_version"        : inputs.properties.get("java_version")
                ])
            }
        } else {
            exclude(file)
        }
    }

    from("${rootDir}/LICENSE")
    from("${rootDir}/icon.png") {
        if (fabricLike) {
            into("assets/${project.parent.property("mod.id")}")
        }
    }
}

tasks.named('sourcesJar').configure {
    duplicatesStrategy = DuplicatesStrategy.INCLUDE
    from delombok.outputs.files
    dependsOn delombok
}

tasks.named("runClient").configure {
    dependsOn tasks.named("build")
}

jar {
    duplicatesStrategy = DuplicatesStrategy.INCLUDE
    from(rootProject.file("LICENSE"))
    from(rootProject.file("README.md"))
    from(rootProject.file("README.en.md"))

    if (authlibVersion >= 50046) {
        exclude("zh/qiushui/mod/multiyggdrasil/auth/MultiYggdrasilUserAuth.class")
        exclude("zh/qiushui/mod/multiyggdrasil/mixin/YggdrasilAuthServiceAccessor.class")
        exclude("zh/qiushui/mod/multiyggdrasil/util/RequestUtil.class")
    }
    exclude("zh/qiushui/mod/multiyggdrasil/util/vap/Patterns.class")
    exclude("zh/qiushui/mod/multiyggdrasil/util/vap/VAPPattern.class")
}

artifacts {
    archives tasks.jar
    archives tasks.sourcesJar
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            groupId = project.group
            artifactId = "${this.project.parent.property("mod.artifact_name")}-${project.name}"
            version = "${this.project.getVersion(this.project.parent)}"

            from(this.project.components.java)
        }
    }

    // See https://docs.gradle.org/current/userguide/publishing_maven.html for information on how to set up publishing.
    repositories {
        // Add repositories to publish to here.
        def MAVEN_URL = System.getenv("MAVEN_URL")
        if (MAVEN_URL != null) {
            maven {
                url MAVEN_URL
                credentials {
                    username System.getenv("MAVEN_USERNAME")
                    password System.getenv("MAVEN_PASSWORD")
                }
            }
        } else {
            mavenLocal()
        }
    }
}

tasks.withType(Javadoc).configureEach { Javadoc task ->
    include("**/api/**")
    task.options.encoding("UTF-8")
    (task.options as CoreJavadocOptions).addStringOption("Xdoclint:none", "-quiet")
}

tasks.withType(JavaCompile).configureEach { JavaCompile task ->
    task.options.encoding = "UTF-8"

    if (mcVersion > 26_00_00) {
        task.options.release.set(25)
    } else if (mcVersion > 1_20_05) {
        task.options.release.set(21)
    } else if (mcVersion > 1_17_01) {
        task.options.release.set(17)
    } else if (mcVersion > 1_16_05) {
        task.options.release.set(16)
    } else {
        task.options.release.set(8)
    }
}

// Setup server default settings.
tasks.named("runServer") {
    defaultCharacterEncoding = "UTF-8"

    doFirst {
        // Agree eula before server init.
        file("${project.projectDir}/run/server/eula.txt").with { File f ->
            {
                if (!f.exists()) {
                    f.parentFile.mkdirs()
                    f.withWriter { BufferedWriter writer ->
                        writer.writeLine("#By changing the setting below to TRUE you are indicating your agreement to our EULA (https://account.mojang.com/documents/minecraft_eula).")
                        writer.writeLine("#${new Date()}")
                        writer.writeLine("eula=true")
                    }
                }
            }
        }
    }
}

tasks.register("cleanRuns", DefaultTask.class) {
    doLast {
        file(loom.runConfigs.client.runDir).parentFile.deleteDir()
    }
}

tasks.register("cleanRunClient", DefaultTask.class) {
    doLast {
        file(loom.runConfigs.client.runDir).deleteDir()
    }
}

tasks.register("cleanRunServer", DefaultTask.class) {
    doLast {
        file(loom.runConfigs.server.runDir).deleteDir()
    }
}

[
        "cleanRuns", "cleanRunClient", "cleanRunServer",
        "runClient", "runServer",
        "preprocessCode", "preprocessResources",
        "preprocessTestCode", "preprocessTestResources"
].forEach { taskName ->
    if (tasks.getNames().contains(taskName)) {
        tasks.named(taskName) {
            it.setGroup("${project.property("mod.id")}")
        }
    }
}

lombok.version = "1.18.34"
