[versions]

fabric-loader = "0.18.4"
jtoml = "1.4.2"

essential = "1.15.48"
preprocessor = "c5abb4fb12"
lombok = "8.7.1"

[libraries]

fabric_loader = { group = "net.fabricmc", name = "fabric-loader", version.ref = "fabric-loader" }
jtoml = { group = "io.github.wasabithumb", name = "jtoml-all", version.ref = "jtoml" }

[plugins]

essential = { id = "gg.essential.loom", version.ref = "essential" }
preprocessor = { id = "com.replaymod.preprocess", version.ref = "preprocessor" }
lombok = { id = "io.freefair.lombok", version.ref = "lombok" }
