[versions]

fabric-loader = "0.19.3"

architectury = "1.17-SNAPSHOT"
shadow = "9.4.0"
preprocessor = "1bb95e0810"
lombok = "8.7.1"

[libraries]

fabric_loader = { group = "net.fabricmc", name = "fabric-loader", version.ref = "fabric-loader" }

[plugins]

architectury-remap = { id = "dev.architectury.loom-remap", version.ref = "architectury" }
architectury-noremap = { id = "dev.architectury.loom-no-remap", version.ref = "architectury" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
preprocessor = { id = "com.replaymod.preprocess", version.ref = "preprocessor" }
lombok = { id = "io.freefair.lombok", version.ref = "lombok" }
