# Dependency Versions
dependencies.minecraft_dependency=>=1.16 <1.16.4
dependencies.minecraft_version=1.16.3
dependencies.authlib_version=10625
dependencies.forge_version=34.1.42
loom.platform=forge

action.minecraft_version=1.16.3
action.mod_loader=forge
action.loader_version=34.1.42
action.java_version=8u312
