# Dependency Versions
dependencies.minecraft_dependency=>=26.1 <26.2
dependencies.minecraft_version=26.1.2
dependencies.authlib_version=70063
dependencies.neoforge_version=26.1.2.71
loom.platform=neoforge

action.minecraft_version=26.1.2
action.mod_loader=neoforge
action.loader_version=26.1.2.71
action.java_version=25
