# Dependency Versions
dependencies.minecraft_dependency=>=1.19 <1.19.3
dependencies.minecraft_version=1.19.2
dependencies.authlib_version=31149
dependencies.fabric_api_version=0.77.0+1.19.2

action.minecraft_version=1.19.2
action.mod_loader=fabric
action.loader_version=0.18.4
action.java_version=16
