# Dependency Versions
dependencies.minecraft_dependency=>=26.1 <26.2
dependencies.minecraft_version=26.1
dependencies.authlib_version=70063
dependencies.forge_version=62.0.1
loom.platform=forge

action.minecraft_version=26.1
action.mod_loader=forge
action.loader_version=62.0.1
action.java_version=25
